// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shorten": {
            "post": {
                "description": "Returns a shortened link for the given URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Shorten an URL",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.shortenUrlRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.shortenUrlResponse"
                        }
                    },
                    "400": {
                        "description": "slug already used",
                        "schema": {
                            "$ref": "#/definitions/api.genericErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.genericErrorResponse"
                        }
                    }
                }
            }
        },
        "/{slug}": {
            "get": {
                "description": "Redirects the user to the original URL in the link",
                "summary": "Redirect from short link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary redirect to URL"
                    },
                    "400": {
                        "description": "link expired",
                        "schema": {
                            "$ref": "#/definitions/api.genericErrorResponse"
                        }
                    },
                    "404": {
                        "description": "link not found",
                        "schema": {
                            "$ref": "#/definitions/api.genericErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/api.genericErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.genericErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.shortenUrlRequest": {
            "type": "object",
            "required": [
                "originalUrl"
            ],
            "properties": {
                "expiresAt": {
                    "description": "needs to be RFC3339 with timezone (or UTC)",
                    "type": "string"
                },
                "originalUrl": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "api.shortenUrlResponse": {
            "type": "object",
            "properties": {
                "shortUrl": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
