definitions:
  dto.PaginationInfoDTO:
    properties:
      currentPage:
        type: integer
      limit:
        type: integer
      nextPage:
        type: integer
      offset:
        type: integer
      previousPage:
        type: integer
      totalPages:
        type: integer
      totalRecords:
        type: integer
    type: object
  dto.RequestInfoDTO:
    properties:
      body:
        additionalProperties: {}
        type: object
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      method:
        type: string
      path:
        type: string
      query:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      realIP:
        type: string
      requestId:
        type: string
      timestamp:
        type: string
      userAgent:
        type: string
    type: object
  v1.createShortLinkRequest:
    properties:
      expiresAt:
        description: needs to be RFC3339 with timezone (or UTC)
        example: "2036-03-09T12:00:00Z"
        type: string
      originalUrl:
        example: https://example.com/very/long/url/that/needs/shortening
        type: string
      slug:
        example: myl1nk
        type: string
    required:
    - originalUrl
    type: object
  v1.genericErrorResponse:
    properties:
      error:
        type: string
    type: object
  v1.listRequestInfoResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/v1.requestInfoDto'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationInfoDTO'
    type: object
  v1.listShortLinksResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/v1.shortLinkDto'
        type: array
      pagination:
        $ref: '#/definitions/dto.PaginationInfoDTO'
    type: object
  v1.requestInfoDto:
    properties:
      body:
        additionalProperties: {}
        type: object
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      id:
        type: integer
      method:
        type: string
      path:
        type: string
      query:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      realIp:
        type: string
      requestId:
        type: string
      timestamp:
        type: string
      userAgent:
        type: string
    type: object
  v1.shortLinkDto:
    properties:
      createdAt:
        example: "2026-03-09T12:00:00Z"
        type: string
      expiresAt:
        example: "2036-03-09T12:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      originalUrl:
        example: https://example.com/very/long/url/that/needs/shortening
        type: string
      shortUrl:
        example: https://short.link/myl1nk
        type: string
      slug:
        example: myl1nk
        type: string
      updatedAt:
        example: "2026-03-10T12:00:00Z"
        type: string
    type: object
  v1.shortLinkInfoResponse:
    properties:
      clickCount:
        type: integer
      createdAt:
        example: "2026-03-09T12:00:00Z"
        type: string
      expiresAt:
        example: "2036-03-09T12:00:00Z"
        type: string
      originalUrl:
        type: string
      shortUrl:
        example: https://short.link/myl1nk
        type: string
      updatedAt:
        example: "2026-03-10T12:00:00Z"
        type: string
    type: object
  v1.shortenUrlRequest:
    properties:
      expiresAt:
        description: needs to be RFC3339 with timezone (or UTC)
        type: string
      originalUrl:
        type: string
      slug:
        type: string
    required:
    - originalUrl
    type: object
  v1.shortenUrlResponse:
    properties:
      shortUrl:
        type: string
      slug:
        type: string
    type: object
  v1.updateShortLinkRequest:
    properties:
      expiresAt:
        description: needs to be RFC3339 with timezone (or UTC)
        example: "2036-03-09T12:00:00Z"
        type: string
      originalUrl:
        type: string
      slug:
        example: myl1nk
        type: string
    type: object
info:
  contact: {}
paths:
  /{slug}:
    get:
      description: Redirects the user to the original URL in the link
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "307":
          description: Temporary redirect to URL
        "404":
          description: link expired
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Redirect from short link
  /v1/admin/info:
    get:
      description: If both params are supplied, ID is used and request ID is ignored
      parameters:
      - description: ID
        in: query
        name: id
        type: integer
      - description: request ID
        in: query
        name: requestId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RequestInfoDTO'
        "400":
          description: invalid request parameters
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "404":
          description: request info not found
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Finds a request info by ID or request ID
      tags:
      - admin
      - info
  /v1/admin/info/list:
    get:
      consumes:
      - application/json
      description: |-
        Supports either combination (offset + limit) or (page size + page) or no pagination
        Either pair must have either both set, or both unset
        If both pairs are supplied, page size + page is used
      parameters:
      - description: size
        in: query
        name: size
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.listRequestInfoResponse'
        "400":
          description: invalid request parameters
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Lists request infos
      tags:
      - admin
      - info
  /v1/admin/info/list/{slug}:
    get:
      consumes:
      - application/json
      description: |-
        Supports either combination (offset + limit) or (page size + page) or no pagination
        Either pair must have either both set, or both unset
        If both pairs are supplied, page size + page is used
      parameters:
      - description: slug
        in: path
        name: slug
        required: true
        type: string
      - description: size
        in: query
        name: size
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.listRequestInfoResponse'
        "400":
          description: invalid request parameters
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Lists request infos for a specific slug
      tags:
      - admin
      - info
  /v1/admin/link:
    post:
      consumes:
      - application/json
      description: Returns a shortened link for the given URL
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.createShortLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.shortLinkDto'
        "400":
          description: slug already used
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Create a short link
      tags:
      - admin
      - links
  /v1/admin/link/id/{id}:
    delete:
      description: Deletes a shortened link
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid link ID
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "404":
          description: link not found
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Delete a short link by ID
      tags:
      - admin
      - links
    get:
      description: Returns a shortened link
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.shortLinkDto'
        "400":
          description: invalid link ID
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "404":
          description: link not found
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Get a short link by ID
      tags:
      - admin
      - links
    put:
      consumes:
      - application/json
      description: Returns updated shortened link
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: fields to update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.updateShortLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.shortLinkDto'
        "400":
          description: invalid request parameters
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "404":
          description: link not found
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Update a short link by ID
      tags:
      - admin
      - links
  /v1/admin/link/list:
    get:
      consumes:
      - application/json
      description: |-
        Supports either combination (offset + limit) or (page size + page) or no pagination
        Either pair must have either both set, or both unset
        If both pairs are supplied, page size + page is used
      parameters:
      - description: size
        in: query
        name: size
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.listShortLinksResponse'
        "400":
          description: invalid request parameters
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Lists short links
      tags:
      - admin
      - links
  /v1/admin/link/slug/{slug}:
    get:
      description: Returns a shortened link
      parameters:
      - description: slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.shortLinkDto'
        "404":
          description: link not found
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Get a short link by slug
      tags:
      - admin
      - links
  /v1/info/{slug}:
    get:
      description: Returns basic information about the short link including original
        URL and click count
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.shortLinkInfoResponse'
        "404":
          description: link not found
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Get short link info by slug
  /v1/shorten:
    post:
      consumes:
      - application/json
      description: Returns a shortened link for the given URL
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.shortenUrlRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.shortenUrlResponse'
        "400":
          description: slug already used
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.genericErrorResponse'
      summary: Shorten an URL
swagger: "2.0"
