// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ProRocketeers/url-shortener/domain/model"
)

func newRequestInfo(db *gorm.DB, opts ...gen.DOOption) requestInfo {
	_requestInfo := requestInfo{}

	_requestInfo.requestInfoDo.UseDB(db, opts...)
	_requestInfo.requestInfoDo.UseModel(&model.RequestInfo{})

	tableName := _requestInfo.requestInfoDo.TableName()
	_requestInfo.ALL = field.NewAsterisk(tableName)
	_requestInfo.ID = field.NewUint(tableName, "id")
	_requestInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_requestInfo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_requestInfo.RequestId = field.NewString(tableName, "request_id")
	_requestInfo.Timestamp = field.NewTime(tableName, "timestamp")
	_requestInfo.RealIP = field.NewString(tableName, "real_ip")
	_requestInfo.UserAgent = field.NewString(tableName, "user_agent")
	_requestInfo.Headers = field.NewField(tableName, "headers")
	_requestInfo.Path = field.NewString(tableName, "path")
	_requestInfo.Method = field.NewString(tableName, "method")
	_requestInfo.Query = field.NewField(tableName, "query")
	_requestInfo.Body = field.NewField(tableName, "body")

	_requestInfo.fillFieldMap()

	return _requestInfo
}

type requestInfo struct {
	requestInfoDo requestInfoDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	RequestId field.String
	Timestamp field.Time
	RealIP    field.String
	UserAgent field.String
	Headers   field.Field
	Path      field.String
	Method    field.String
	Query     field.Field
	Body      field.Field

	fieldMap map[string]field.Expr
}

func (r requestInfo) Table(newTableName string) *requestInfo {
	r.requestInfoDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r requestInfo) As(alias string) *requestInfo {
	r.requestInfoDo.DO = *(r.requestInfoDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *requestInfo) updateTableName(table string) *requestInfo {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.RequestId = field.NewString(table, "request_id")
	r.Timestamp = field.NewTime(table, "timestamp")
	r.RealIP = field.NewString(table, "real_ip")
	r.UserAgent = field.NewString(table, "user_agent")
	r.Headers = field.NewField(table, "headers")
	r.Path = field.NewString(table, "path")
	r.Method = field.NewString(table, "method")
	r.Query = field.NewField(table, "query")
	r.Body = field.NewField(table, "body")

	r.fillFieldMap()

	return r
}

func (r *requestInfo) WithContext(ctx context.Context) *requestInfoDo {
	return r.requestInfoDo.WithContext(ctx)
}

func (r requestInfo) TableName() string { return r.requestInfoDo.TableName() }

func (r requestInfo) Alias() string { return r.requestInfoDo.Alias() }

func (r requestInfo) Columns(cols ...field.Expr) gen.Columns { return r.requestInfoDo.Columns(cols...) }

func (r *requestInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *requestInfo) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["request_id"] = r.RequestId
	r.fieldMap["timestamp"] = r.Timestamp
	r.fieldMap["real_ip"] = r.RealIP
	r.fieldMap["user_agent"] = r.UserAgent
	r.fieldMap["headers"] = r.Headers
	r.fieldMap["path"] = r.Path
	r.fieldMap["method"] = r.Method
	r.fieldMap["query"] = r.Query
	r.fieldMap["body"] = r.Body
}

func (r requestInfo) clone(db *gorm.DB) requestInfo {
	r.requestInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r requestInfo) replaceDB(db *gorm.DB) requestInfo {
	r.requestInfoDo.ReplaceDB(db)
	return r
}

type requestInfoDo struct{ gen.DO }

func (r requestInfoDo) Debug() *requestInfoDo {
	return r.withDO(r.DO.Debug())
}

func (r requestInfoDo) WithContext(ctx context.Context) *requestInfoDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r requestInfoDo) ReadDB() *requestInfoDo {
	return r.Clauses(dbresolver.Read)
}

func (r requestInfoDo) WriteDB() *requestInfoDo {
	return r.Clauses(dbresolver.Write)
}

func (r requestInfoDo) Session(config *gorm.Session) *requestInfoDo {
	return r.withDO(r.DO.Session(config))
}

func (r requestInfoDo) Clauses(conds ...clause.Expression) *requestInfoDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r requestInfoDo) Returning(value interface{}, columns ...string) *requestInfoDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r requestInfoDo) Not(conds ...gen.Condition) *requestInfoDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r requestInfoDo) Or(conds ...gen.Condition) *requestInfoDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r requestInfoDo) Select(conds ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r requestInfoDo) Where(conds ...gen.Condition) *requestInfoDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r requestInfoDo) Order(conds ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r requestInfoDo) Distinct(cols ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r requestInfoDo) Omit(cols ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r requestInfoDo) Join(table schema.Tabler, on ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r requestInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r requestInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r requestInfoDo) Group(cols ...field.Expr) *requestInfoDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r requestInfoDo) Having(conds ...gen.Condition) *requestInfoDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r requestInfoDo) Limit(limit int) *requestInfoDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r requestInfoDo) Offset(offset int) *requestInfoDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r requestInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *requestInfoDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r requestInfoDo) Unscoped() *requestInfoDo {
	return r.withDO(r.DO.Unscoped())
}

func (r requestInfoDo) Create(values ...*model.RequestInfo) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r requestInfoDo) CreateInBatches(values []*model.RequestInfo, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r requestInfoDo) Save(values ...*model.RequestInfo) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r requestInfoDo) First() (*model.RequestInfo, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RequestInfo), nil
	}
}

func (r requestInfoDo) Take() (*model.RequestInfo, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RequestInfo), nil
	}
}

func (r requestInfoDo) Last() (*model.RequestInfo, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RequestInfo), nil
	}
}

func (r requestInfoDo) Find() ([]*model.RequestInfo, error) {
	result, err := r.DO.Find()
	return result.([]*model.RequestInfo), err
}

func (r requestInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RequestInfo, err error) {
	buf := make([]*model.RequestInfo, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r requestInfoDo) FindInBatches(result *[]*model.RequestInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r requestInfoDo) Attrs(attrs ...field.AssignExpr) *requestInfoDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r requestInfoDo) Assign(attrs ...field.AssignExpr) *requestInfoDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r requestInfoDo) Joins(fields ...field.RelationField) *requestInfoDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r requestInfoDo) Preload(fields ...field.RelationField) *requestInfoDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r requestInfoDo) FirstOrInit() (*model.RequestInfo, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RequestInfo), nil
	}
}

func (r requestInfoDo) FirstOrCreate() (*model.RequestInfo, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RequestInfo), nil
	}
}

func (r requestInfoDo) FindByPage(offset int, limit int) (result []*model.RequestInfo, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r requestInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r requestInfoDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r requestInfoDo) Delete(models ...*model.RequestInfo) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *requestInfoDo) withDO(do gen.Dao) *requestInfoDo {
	r.DO = *do.(*gen.DO)
	return r
}
